### ISSUE TITLE
TODO - Pubs+Presentation Task: Relation Extraction Paper

### ISSUE THREAD

**Issue by tuh8888** [tuh8888/Dep2Rel#26]
**Pub or Presentation:** Relation Extraction Work for Dep2Rel with CRAFT and BioCreative results.

**Submission Site:** 
- [ ] TODO

**Due Date:**
- [ ] TODO

**Comment by tuh8888** [comment]
** What would I need to finish to publish? **

- [ ] Parameter tuning
- [ ] Achieve new state of the art for BioCreative
- [ ] Context path analysis.
  - [ ] Cluster context paths for different relations
    - [ ] PCA plot
  - [ ] Context path length
    - [ ] Distribution of lengths
- [ ] Incorporate concept recognizer
- [ ] Evaluate different syntax parsers
- [ ] Chemical tokenizer
- [ ]

**Comment by tuh8888** [comment]
@LEHunter  Can you think of any other things I should look into before putting this away?
